const {
    NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY,
} = process.env;


export const envConfig = () =>  ({
    SUPABASE_URL: NEXT_PUBLIC_SUPABASE_URL!,
    SUPABASE_KEY: NEXT_PUBLIC_SUPABASE_ANON_KEY!,
});

